[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "sha2raw"
]

[patch.crates-io]
fil-sapling-crypto = { git = "https://github.com/filecoin-project/sapling-crypto", branch = "fix/compile-nonx86" }
fff = { git = "https://github.com/filecoin-project/ff", branch = "fix-arch" }
